#9 Member 패키지 리팩터링
f-lab-edu/interviewPrep pull request #10
Opened 2023-07-25 11:46 UTC by LeeJaeYun7

- Member 패키지를 리팩터링했습니다.

2023-07-27 15:11 UTC, f-lab-moony requested changes
고생많으셨어요 ~
코멘트가 좀 많은데, 한번 확인해보시고 다시 올려주시면 좋을 것 같아요 ~

2023-07-27 15:11 UTC, f-lab-moony commented on src/main/java/com/example/interviewPrep/quiz/member/service/MemberService.java
> +          UserDetails userDetails = (UserDetails)principal;
이거 세팅은 MemberContext로 하는것 같은데, 그거 쓰시면 `Long.parseLong`도 매번 안해도 되지 않을까요 ?

2023-07-27 15:11 UTC, f-lab-moony commented on src/main/java/com/example/interviewPrep/quiz/member/service/MemberService.java
> +        if(newNickName != null){
not null 체크는 setNickName 안에서 해도 되지 않을까요 ?

2023-07-27 15:11 UTC, f-lab-moony commented on src/main/java/com/example/interviewPrep/quiz/member/service/MemberService.java
> +    public void updateEmail(Member member, String newEmail){
이 두개는 duplicate 체크와 update로 나누는게 어떨까요 ?

2023-07-27 15:11 UTC, f-lab-moony commented on src/main/java/com/example/interviewPrep/quiz/member/service/MemberService.java
> +    public boolean isValidPassword(Member member, String memberPassword, String inputPassword, String newPassword){
이름은 isValid~~ 인데 내부에서는 암호도 바꾸고 다른 추가작업이 있는 것 같아요 ?

2023-07-27 15:11 UTC, f-lab-moony commented on src/main/java/com/example/interviewPrep/quiz/member/service/MemberService.java
> +        memberRepository.save(member);
이 부분은 필요가 없지 않을까요 ?

2023-07-27 15:11 UTC, f-lab-moony commented on src/test/java/com/example/interviewPrep/quiz/Member/service/AuthenticationServiceTest.java
> +        assertNotNull(loginResponseDTO, "Expected non-null LoginResponseDTO");
검증은 `assertThat()`으로 시작하시는 걸 추천드려요 ~

2023-07-27 15:11 UTC, f-lab-moony commented on src/test/java/com/example/interviewPrep/quiz/Member/service/AuthenticationServiceTest.java
> +    @DisplayName("login failure by wrong email")
👍

2023-07-27 15:11 UTC, f-lab-moony commented on src/test/java/com/example/interviewPrep/quiz/Member/service/AuthenticationServiceTest.java
> +    @DisplayName("login failure by wrong password")
DisplayName은 테스트 설명부분이라 왠만하면 한글로 설명이 되게 적어주시는게 좋아요 ~

2023-07-29 14:45 UTC, LeeJaeYun7 commented on src/main/java/com/example/interviewPrep/quiz/member/controller/MemberController.java
> +    @Autowired
생성자가 하나일 경우, @Autowired를 생략할 수 있다는 내용을 깜박해서 그런 것 같습니다!
수정해보겠습니다

2023-07-30 12:37 UTC, f-lab-moony requested changes
혹시 피드백 반영 어떻게 진행하고 계신걸까요 ~?
이전 피드백에 코멘트가 달린 흔적이 있는데, 피드백 반영분에는 적용되지 않은 것 같아 여쭤봅니다 ~

2023-07-30 12:37 UTC, f-lab-moony commented on src/main/java/com/example/interviewPrep/quiz/member/dto/MemberDTO.java
> +        if (email == null || password == null || nickName == null || newPassword == null || type == null) {
생성자에서 잡아주실거면 위에 `@NotNull` 은 필요 없을 것 같아요 ?
그리고 이렇게 검사하면 어떤 값이 null인지 메세지로 파악이 안되지 않을까요 ?
저는 보통 `Objects.requireNonNull` 메서드를 이용하는 편입니다.

2023-07-30 12:37 UTC, f-lab-moony commented on src/test/java/com/example/interviewPrep/quiz/Member/domain/MemberTest.java
> +    @DisplayName("member create")
생성자가 두개라면, 테스트도 두개가 되어야 하지 않을까요 ?
그리고 저번에 코멘트 한 내용인데, 굳이 생성자가 두개여야 할 필요가 있을까요 ?

2023-07-30 12:37 UTC, f-lab-moony commented on src/test/java/com/example/interviewPrep/quiz/Member/dto/MemberDTOTest.java
> +    @DisplayName("memberDTO create with null value")
null체크가 여러개가 있을 것 같은데, `@ParameterizedTest` 를 이용해보는 건 어떨까요 ?

2023-07-31 04:15 UTC, LeeJaeYun7 commented on src/main/java/com/example/interviewPrep/quiz/member/controller/MemberController.java
> +    public ResultResponse<Member> getUserInfo(){
장점
-개발자가 원하는대로 커스텀해서 사용할 수 있다
- 통일된 양식으로 ResponseEntity를 만들 수 있다

단점
-추상 계층이 하나가 추가된다
-코드 오버헤드가 늘어난다
-스프링의 built-in 기능을 사용할 수 없다
(ex) 컨텐츠 negotiation, HTTP 헤더 조작, 자동 응답 코드 핸들링 등)

2023-07-31 04:24 UTC, LeeJaeYun7 commented on src/main/java/com/example/interviewPrep/quiz/member/controller/MemberController.java
>      @PostMapping("signup")
그러면 이전 버전의 API를 유지하고 새로운 버전의 API를 추가할 때면, 
기존의 것은 그대로 놔두고, /v2/members를 추가하는 방식으로 사용하는 것일까요?

2023-07-31 04:24 UTC, LeeJaeYun7 commented on src/main/java/com/example/interviewPrep/quiz/member/domain/Member.java
> +    public Member() {
넵 확인했습니다

2023-07-31 04:27 UTC, LeeJaeYun7 commented on src/main/java/com/example/interviewPrep/quiz/member/domain/Member.java
> +    public Member(String email, String password, String type, String nickName, String name, String picture, Role role){
이 부분 한 번 다시 확인해보겠습니다

2023-07-31 04:31 UTC, LeeJaeYun7 commented on src/main/java/com/example/interviewPrep/quiz/member/dto/LoginRequestDTO.java
> -@NoArgsConstructor
넵 확인했습니다~

2023-07-31 04:39 UTC, LeeJaeYun7 commented on src/main/java/com/example/interviewPrep/quiz/member/controller/MemberController.java
>      @PostMapping("signup")
그리고 저렇게 버전을 표시해줄려면, 앞에 @RequestMapping("/members")를 붙여주는 것보다,
각각의 메소드에 독립적으로 선언해주어야 할 것 같은데, 맞을까요?
![image](https://github.com/f-lab-edu/interviewPrep/assets/134198681/e88b4937-b080-4f7e-9b82-1c2fb361cc8e)

2023-07-31 04:43 UTC, LeeJaeYun7 commented on src/main/java/com/example/interviewPrep/quiz/member/controller/MemberController.java
>      @PostMapping("signup")
반영 완료

2023-07-31 05:09 UTC, LeeJaeYun7 commented on src/main/java/com/example/interviewPrep/quiz/member/service/AuthenticationService.java
> +        if(!passwordCheck(member.getPassword(), password)) {
넵 네이밍을 좀 더 직관적으로 수정했습니다

2023-07-31 05:10 UTC, LeeJaeYun7 commented on src/main/java/com/example/interviewPrep/quiz/member/service/AuthenticationService.java
> +        if(!passwordCheck(member.getPassword(), password)) {
넵 네이밍을 좀 더 직관적으로 isMatchPassword로 수정했습니다!

2023-07-31 05:15 UTC, LeeJaeYun7 commented on src/main/java/com/example/interviewPrep/quiz/member/service/AuthenticationService.java
> +        String memberId = getMemberId(token);
넵 파라미터 이름 refreshToken으로 수정했습니다

2023-07-31 05:15 UTC, LeeJaeYun7 commented on src/main/java/com/example/interviewPrep/quiz/member/service/AuthenticationService.java
> +        List<String> tokens = new ArrayList<>();
넵 List.of 반영해서 수정했습니다

2023-07-31 05:16 UTC, LeeJaeYun7 commented on src/main/java/com/example/interviewPrep/quiz/member/service/AuthenticationService.java
> +        if(!isValidRefreshToken(token, memberId)){
넵 수정했습니다!

2023-07-31 05:24 UTC, LeeJaeYun7 commented on src/main/java/com/example/interviewPrep/quiz/member/service/AuthenticationService.java
> +        return makeLoginResponseDTO(memberId, role);
LoginResponseDTO를 원래는 빌더 패턴으로 만들었었는데, 
좀 코드가 긴것 같아서 따로 메소드로 빼서 만들었었습니다.
그런데 원래 방식대로 변경해보았습니다.

2023-07-31 05:25 UTC, LeeJaeYun7 commented on src/main/java/com/example/interviewPrep/quiz/member/service/AuthenticationService.java
> +    public Role setRoleType(String token){
getRoleType이 맞는 것 같습니다.
수정했습니다

2023-07-31 05:50 UTC, LeeJaeYun7 commented on src/main/java/com/example/interviewPrep/quiz/member/service/AuthenticationService.java
> +        if(roleStr.equals("USER")) role = Role.USER;
if문에 {}을 선언하지 않으면, 추후에 코드를 추가하는 경우가 발생했을 때, 버그로 이어질 수 있다는 문제가 있습니다

2023-07-31 05:53 UTC, LeeJaeYun7 commented on src/main/java/com/example/interviewPrep/quiz/member/service/AuthenticationService.java
> +        if(roleStr.equals("USER")) role = Role.USER;
if 문 양식을 변경해서 반영했습니다

2023-07-31 05:55 UTC, LeeJaeYun7 commented on src/main/java/com/example/interviewPrep/quiz/member/service/AuthenticationService.java
> +
넵 Intellij IDE에서 이렇게 적용해봤는데,
혹시 적용이 안된걸까요?
![image](https://github.com/f-lab-edu/interviewPrep/assets/134198681/68a6b0d0-ba32-45bc-b28c-a5fb1994f922)

2023-07-31 05:57 UTC, LeeJaeYun7 commented on src/main/java/com/example/interviewPrep/quiz/member/service/AuthenticationService.java
> +    public void deleteMemberOnRedis(String memberId){
RedisService라는 클래스를 만들어서 처리하는 것이 좋을 것 같습니다

2023-07-31 06:16 UTC, LeeJaeYun7 commented on src/main/java/com/example/interviewPrep/quiz/member/service/AuthenticationService.java
> +    public void deleteMemberOnRedis(String memberId){
RedisService 라는 클래스를 추가해서 RedisDao에 관한 접근을 이 클래스에서 처리하도록 수정하였습니다

2023-07-31 06:28 UTC, LeeJaeYun7 commented on src/main/java/com/example/interviewPrep/quiz/member/service/MemberService.java
> +        return memberRepository.findByEmail(email).isPresent();
넵 반영했습니다

2023-07-31 06:49 UTC, LeeJaeYun7 commented on src/main/java/com/example/interviewPrep/quiz/member/service/MemberService.java
> +        if(newNickName != null){
넵 setNickName안에서 null 체크를 하고 NPE를 리턴하도록 수정하였습니다

2023-08-01 06:20 UTC, LeeJaeYun7 commented on src/main/java/com/example/interviewPrep/quiz/member/service/MemberService.java
> +    public void updateEmail(Member member, String newEmail){
반영했습니다

2023-08-01 06:24 UTC, LeeJaeYun7 commented on src/main/java/com/example/interviewPrep/quiz/member/service/MemberService.java
> +    public boolean isValidPassword(Member member, String memberPassword, String inputPassword, String newPassword){
넵 밖에서 처리하도록 수정했습니다

2023-08-01 06:25 UTC, LeeJaeYun7 commented on src/main/java/com/example/interviewPrep/quiz/member/service/MemberService.java
> +        memberRepository.save(member);
넵 이 부분 밖에서 처리하도록 수정했습니다

2023-08-01 06:31 UTC, LeeJaeYun7 commented on src/test/java/com/example/interviewPrep/quiz/Member/domain/MemberTest.java
> +    @DisplayName("member create")
넵 빌더 패턴으로 생성하도록 수정했습니다

2023-08-01 16:37 UTC, LeeJaeYun7 commented on src/test/java/com/example/interviewPrep/quiz/Member/service/AuthenticationServiceTest.java
> +        assertNotNull(loginResponseDTO, "Expected non-null LoginResponseDTO");
넵 반영했습니다

2023-08-02 03:44 UTC, LeeJaeYun7 commented on src/test/java/com/example/interviewPrep/quiz/Member/dto/MemberDTOTest.java
> +    @DisplayName("memberDTO create with null value")
@ParameterizedTest 반영해서 완료했습니다

2023-08-02 06:41 UTC, LeeJaeYun7 commented on src/main/java/com/example/interviewPrep/quiz/member/controller/MemberController.java
> +    public ResultResponse<Member> signUp(@RequestBody SignUpRequestDTO memberDTO) throws Exception {
아무런 역할을 하고 있지 않아서 제외시켰습니다

2023-08-04 16:37 UTC, f-lab-moony commented on src/main/java/com/example/interviewPrep/quiz/member/controller/MemberController.java
> +    public ResultResponse<Member> getUserInfo(){
멘토링 시간에 말씀 드리긴 했지만, 이 구조는 api를 사용하는 클라이언트 입장에서 가장 불편을 크게 느끼는 구조에요, 공통된 레이어가 꼭 필요하거나 (페이징 응답이라던지) 합의 된 경우가 아니라면 응답객체를 그대로 리턴하는 걸 추천합니다!

2023-08-04 16:39 UTC, merged

2023-08-16 09:32 UTC, LeeJaeYun7 commented on src/main/java/com/example/interviewPrep/quiz/member/controller/MemberController.java
> +    public ResultResponse<Member> getUserInfo(){
응답 객체를 그대로 리턴