#10 Question 패키지 리팩토링 및 테스트 작성
f-lab-edu/interviewPrep pull request #11
Opened 2023-08-15 06:36 UTC by LeeJaeYun7

Question 패키지를 리팩터링하고, 테스트를 작성했습니다

2023-08-17 11:27 UTC, f-lab-moony requested changes
고생 많으셨어요 ~ 코멘트 좀 남겨 두었는데, 확인 후 리뷰 재요청 해주세요 ~

2023-08-17 11:27 UTC, f-lab-moony commented on src/main/java/com/example/interviewPrep/JpaAuditingConfiguration.java
> +@EnableJpaAuditing
요거 메인 클래스에 선언해도 되지 않나요 ?

2023-08-17 11:27 UTC, f-lab-moony commented on src/main/java/com/example/interviewPrep/quiz/question/controller/QuestionController.java
> +    @GetMapping("/api/v1/question/single/{id}")
중간에 single 굳이 안써도 되지 않을까요 ~?

2023-08-17 11:27 UTC, f-lab-moony commented on src/main/java/com/example/interviewPrep/quiz/question/controller/QuestionController.java
> +    @GetMapping({"/api/v1/question/{type}", ""})
type은 id의 성격이 아니라서 by-type 같이 추가 정보를 요구한다는걸 나타내주는게 좋을 것 같아요

2023-08-17 11:27 UTC, f-lab-moony commented on src/main/java/com/example/interviewPrep/quiz/question/controller/QuestionController.java
> +    @GetMapping({"/api/v1/question/{type}", ""})
뒤에 빈 문자열은 무슨 뜻일까요 ?

2023-08-17 11:27 UTC, f-lab-moony commented on src/main/java/com/example/interviewPrep/quiz/question/dto/QuestionRequest.java
> +@Builder
빌더는 생성자에 달아주는걸 추천합니다 ~

2023-08-17 11:27 UTC, f-lab-moony commented on src/main/java/com/example/interviewPrep/quiz/question/service/QuestionService.java
> +                .type(questionRequest.getType())
이 Question을 만드는 책임은 QuestionRequest가 가져가도 되지 않을까요 ?

2023-08-17 11:27 UTC, f-lab-moony commented on src/main/java/com/example/interviewPrep/quiz/question/service/QuestionService.java
> +        return QuestionResponse.builder()
여기도 QuestionResponse에 정적 팩토리 메서드를 추가해보면 어떨까요 ?

2023-08-17 11:27 UTC, f-lab-moony commented on src/main/java/com/example/interviewPrep/quiz/question/service/QuestionService.java
> +        return questionRepository.findById(id).orElseThrow(() -> new CommonException(NOT_FOUND_QUESTION));
요청받은 id가 뭐였는지도 메세지에 드러나면 좋을 것 같아요 ~

2023-08-17 11:27 UTC, f-lab-moony commented on src/main/java/com/example/interviewPrep/quiz/question/service/QuestionService.java
> +                        .status(answers.contains(q.getId()))
contains 연산을 수행할때 List와 Set 중 뭐가 유리할까요 ?

2023-08-17 11:27 UTC, f-lab-moony commented on src/main/java/com/example/interviewPrep/quiz/question/service/QuestionService.java
> +        Page<Question> questions = findQuestionsByTypeAndPageable(type, pageable);
사실 지금 수준에선 문제가 없겠지만, offset 방식의 페이징은 서비스가 커지면 반드시 문제가 생겨요. more 방식 페이징에 대해서 한번 찾아보시고 습관 들이시는걸 추천합니다~

2023-08-17 11:27 UTC, f-lab-moony commented on src/test/java/com/example/interviewPrep/quiz/Question/controller/QuestionCreateWebControllerTest.java
> +        validQuestionRequest = QuestionRequest.builder()
검증하려는 데이터는 그 테스트 내부에서 정의되는게 테스트 가독성을 더 높일 수 있다고 생각합니다 ~

2023-08-17 11:27 UTC, f-lab-moony commented on src/test/java/com/example/interviewPrep/quiz/Question/controller/QuestionDeleteWebControllerTest.java
> +        given(questionService.deleteQuestion(1000L)).willThrow(new QuestionNotFoundException(1000L));
이거 이렇게 선언하면 아래 테스트들 잘 돌아가나요 ?

2023-08-20 08:33 UTC, LeeJaeYun7 commented on src/main/java/com/example/interviewPrep/JpaAuditingConfiguration.java
> +@EnableJpaAuditing
테스트 작성하는데 이걸 따로 선언해줘야 하더라고요
그래서 선언했습니다!

2023-08-20 08:33 UTC, LeeJaeYun7 commented on src/main/java/com/example/interviewPrep/quiz/question/controller/QuestionController.java
> +    @GetMapping("/api/v1/question/single/{id}")
네 맞습니다. 그 부분은 수정해보겠습니다

2023-08-20 08:35 UTC, LeeJaeYun7 commented on src/main/java/com/example/interviewPrep/quiz/question/controller/QuestionController.java
> +    @GetMapping({"/api/v1/question/{type}", ""})
그럼  @GetMapping({"/api/v1/question/by/{type}", ""})
이렇게 나타내는걸 말씀하시는 걸까요?

2023-08-20 08:35 UTC, LeeJaeYun7 commented on src/main/java/com/example/interviewPrep/quiz/question/controller/QuestionController.java
> +    @GetMapping({"/api/v1/question/{type}", ""})
type이 null일때를 의미하는 것 같은데... 굳이 필요하지 않을 것 같습니다

2023-08-20 08:39 UTC, LeeJaeYun7 commented on src/main/java/com/example/interviewPrep/quiz/question/dto/QuestionRequest.java
> +@Builder
넵 확인했습니다 
https://johngrib.github.io/wiki/pattern/builder/

2023-08-20 08:45 UTC, LeeJaeYun7 commented on src/main/java/com/example/interviewPrep/quiz/question/service/QuestionService.java
> +        return QuestionResponse.builder()
정적 팩토리 메서드를 추가했을 때의 이점이 어떤 것이 있을까요?

2023-08-20 08:46 UTC, LeeJaeYun7 commented on src/main/java/com/example/interviewPrep/quiz/question/service/QuestionService.java
> +        return questionRepository.findById(id).orElseThrow(() -> new CommonException(NOT_FOUND_QUESTION));
id는 Quesiton의 id인데 이 부분도 반영해보겠습니다

2023-08-20 08:49 UTC, LeeJaeYun7 commented on src/main/java/com/example/interviewPrep/quiz/question/service/QuestionService.java
> +        Page<Question> questions = findQuestionsByTypeAndPageable(type, pageable);
https://green-bin.tistory.com/m/23
넵 참고해보겠습니다

2023-08-20 08:52 UTC, LeeJaeYun7 commented on src/main/java/com/example/interviewPrep/quiz/question/service/QuestionService.java
> +                        .status(answers.contains(q.getId()))
ArrayList를 사용할 경우엔 O(N)이지만,
HashSet을 사용할 경우엔 O(1) 이므로, Set을 사용하는 편이 유리할 것 같습니다

2023-08-20 08:52 UTC, LeeJaeYun7 commented on src/test/java/com/example/interviewPrep/quiz/Question/controller/QuestionCreateWebControllerTest.java
> +        validQuestionRequest = QuestionRequest.builder()
넵 확인했습니다

2023-08-20 13:48 UTC, f-lab-moony commented on src/main/java/com/example/interviewPrep/JpaAuditingConfiguration.java
> +@EnableJpaAuditing
테스트 작성과 어떤 관계가 있는걸까요 ?

2023-08-20 13:52 UTC, f-lab-moony commented on src/main/java/com/example/interviewPrep/quiz/question/controller/QuestionController.java
> +    @GetMapping({"/api/v1/question/{type}", ""})
`@GetMapping("/api/v1/questions/by-type/{type}")` 이런식으로 말씀드렸어요 ~ api를 쓰는 사람 입장에서 endpoint는 메서드같은 역할을 하기때문에 메서드 이름처럼 의미가 잘 드러나게 하는게 좋을 것 같아요

그리고 이건 다른데서 썼던거같긴 한데 저 뒤의 ""는 왜 추가해주신걸까요 ?

p.s `@` 을 그냥 쓰시면 다른 사람이 멘션되니까 `` 요거로 감싸주시는게 좋아요 ~

2023-08-20 13:55 UTC, f-lab-moony commented on src/main/java/com/example/interviewPrep/quiz/question/controller/QuestionController.java
> +    @GetMapping({"/api/v1/question/{type}", ""})
type이 null일때라고 생각하신 이유가 있을까요 ? 연결되는 endpoint가 복수개라는 뜻으로 보이는데, 추가 path 없이 host만 입력된 요청도 얘가 받겠다 라는 뜻이 아닐까요 ?

2023-08-20 13:57 UTC, f-lab-moony commented on src/main/java/com/example/interviewPrep/quiz/question/service/QuestionService.java
> +        return questionRepository.findById(id).orElseThrow(() -> new CommonException(NOT_FOUND_QUESTION));
뜻이 약간 잘못 전달된 것 같아서 .. 파라미터 명을 바꾸자는게 아니라 메세지에 드러났으면 좋겠다는 의견이었습니다 ~

2023-08-21 02:44 UTC, LeeJaeYun7 commented on src/main/java/com/example/interviewPrep/quiz/question/service/QuestionService.java
> +                .type(questionRequest.getType())
넵 확인했습니다 정적 팩터리 메서드를 만들어서 해결했습니다.
반영 완료

2023-08-21 02:45 UTC, LeeJaeYun7 commented on src/main/java/com/example/interviewPrep/quiz/question/service/QuestionService.java
> +        return QuestionResponse.builder()
정적 팩터리 메서드가 생성자보다 좋은 장점

1. 이름을 가질 수 있다
2. 호출될 때마다 인스턴스를 새로 생성하지는 않아도 된다
3. 반환 타입의 하위 타입 객체를 반환할 수 있는 능력이 있다
4. 입력 매개변수에 따라 매번 다른 클래스의 객체를 반환할 수 있다
5. 정적 팩터리 메서드를 작성하는 시점에는 반환할 객체의 클래스가 존재하지 않아도 된다.

2023-08-21 04:30 UTC, LeeJaeYun7 commented on src/main/java/com/example/interviewPrep/quiz/question/controller/QuestionController.java
> +    @GetMapping("/api/v1/question/single/{id}")
반영 완료

2023-08-21 04:38 UTC, LeeJaeYun7 commented on src/main/java/com/example/interviewPrep/quiz/question/controller/QuestionController.java
> +    @GetMapping({"/api/v1/question/{type}", ""})
반영 완료

2023-08-21 04:39 UTC, LeeJaeYun7 commented on src/main/java/com/example/interviewPrep/quiz/question/controller/QuestionController.java
> +    @GetMapping({"/api/v1/question/{type}", ""})
다시 생각해보니 말씀하신게 맞는 것 같습니다!

2023-08-21 04:59 UTC, LeeJaeYun7 commented on src/main/java/com/example/interviewPrep/quiz/question/dto/QuestionRequest.java
> +@Builder
반영 완료

2023-08-21 04:59 UTC, LeeJaeYun7 commented on src/main/java/com/example/interviewPrep/quiz/question/service/QuestionService.java
> +        return QuestionResponse.builder()
반영 완료

2023-08-21 04:59 UTC, LeeJaeYun7 commented on src/main/java/com/example/interviewPrep/quiz/question/service/QuestionService.java
> +        return questionRepository.findById(id).orElseThrow(() -> new CommonException(NOT_FOUND_QUESTION));
반영 완료

2023-08-21 04:59 UTC, LeeJaeYun7 commented on src/main/java/com/example/interviewPrep/quiz/question/service/QuestionService.java
> +                        .status(answers.contains(q.getId()))
반영 완료

2023-08-24 07:39 UTC, LeeJaeYun7 commented on src/main/java/com/example/interviewPrep/JpaAuditingConfiguration.java
> +@EnableJpaAuditing
테스트 할 때 깨지는 부분이 있었는데...
다시 해보니 InterviewPrepApplication 클래스에 @EnableJpaAuditing 하는 걸로 해결되서 
수정해서 커밋했습니다

2023-08-24 15:18 UTC, f-lab-moony approved these changes
고생 많으셨습니다 ~
코멘트를 좀 남겨 두었는데, 요거는 머지 해둘게요 ~ 확인 후 반영 부탁드립니다 ~

2023-08-24 15:18 UTC, f-lab-moony commented on src/main/java/com/example/interviewPrep/quiz/question/controller/QuestionController.java
> +    public ResponseEntity<Void> create(@RequestBody QuestionRequest questionRequest) {
요전에 말씀 드리긴 했는데 ResponseEntity 꼭 써야할까요 ~?

2023-08-24 15:18 UTC, f-lab-moony commented on src/main/java/com/example/interviewPrep/quiz/question/controller/QuestionController.java
> +    public ResponseEntity<Page<QuestionResponse>> getQuestionsByType(@PathVariable(required = false) String type, @PageableDefault(size = 10) Pageable pageable) {
응답을 Spring에서 제공하는 클래스인 Page로 감싸면 어떤 단점이 있을 수 있을까요 ?

2023-08-24 15:18 UTC, f-lab-moony commented on src/main/java/com/example/interviewPrep/quiz/question/controller/QuestionController.java
> +    public ResponseEntity<Void> update(@PathVariable Long id, @RequestBody @Valid QuestionRequest questionRequest) {
create랑 update에서 같은 request를 쓰는 이유는 뭘까요 ~?

2023-08-24 15:18 UTC, f-lab-moony commented on src/main/java/com/example/interviewPrep/quiz/question/controller/QuestionController.java
> +    @GetMapping("/all")
count가 질문의 갯수를 리턴한다면 `/all` 은 안어울리는 이름 같아요

2023-08-24 15:18 UTC, f-lab-moony commented on src/main/java/com/example/interviewPrep/quiz/question/domain/Question.java
> +    public static Question createQuestionByQuestionRequest(QuestionRequest questionRequest) {
의존성 방향을 바깥에서 안쪽으로만 허용해주시는 습관을 들이시는게 좋을 것 같아요. `클린 아키텍처`에 대해서 한번 찾아보시는 걸 추천드립니다 ~

2023-08-24 15:18 UTC, f-lab-moony commented on src/main/java/com/example/interviewPrep/quiz/question/dto/QuestionResponse.java
> +    public static QuestionResponse createQuestionResponse(Question question){
요런건 보통 이름을 그냥 of나 from 으로 쓰는 편이에요!

2023-08-24 15:18 UTC, merged