#12 Mock interview 기능
f-lab-edu/interviewPrep pull request #16
Opened 2023-08-16 04:06 UTC by LeeJaeYun7

- Mock Interview 기능과 관련한 Entity 클래스를 추가했습니다

2023-08-19 11:14 UTC, f-lab-moony requested changes
고생 많으셨습니다 ~ 코멘트를 좀 남겨 뒀는데, 확인 후 리뷰 재요청 부탁드려요 ~

2023-08-19 11:14 UTC, f-lab-moony commented on src/main/java/com/example/interviewPrep/quiz/MemberInterview/domain/MemberInterview.java
> +public class MemberInterview {
이 Entity가 없으면 다대다 맵핑이 불가능한가요 ? 아니라면 굳이 추가한 이유는 뭘까요 ?

2023-08-19 11:14 UTC, f-lab-moony commented on src/main/java/com/example/interviewPrep/quiz/MemberInterview/domain/MemberInterview.java
> +public class MemberInterview {
Member와 Interview가 다대다여야 하는 이유가 있을까요 ?

2023-08-19 11:14 UTC, f-lab-moony commented on src/main/java/com/example/interviewPrep/quiz/interview/controller/InterviewController.java
> +
빈줄이 너무 많네요 컨벤션 적용해주시는게 좋을 것 같아요 ~

2023-08-19 11:14 UTC, f-lab-moony commented on src/main/java/com/example/interviewPrep/quiz/interview/controller/InterviewController.java
> +@CrossOrigin("*")
클래스별로 관리하는 이유가 있을까요 ?

2023-08-19 11:14 UTC, f-lab-moony commented on src/main/java/com/example/interviewPrep/quiz/interview/controller/InterviewController.java
> +    public ResultResponse<?> createInterview(@RequestBody @Valid InterviewRequest interviewRequest){
`@Valid`가 동작하고 있나요 ?

2023-08-19 11:14 UTC, f-lab-moony commented on src/main/java/com/example/interviewPrep/quiz/interview/controller/InterviewController.java
> +    @PostMapping("/api/v1/interview")
보통 엔드포인트에 도메인은 복수로 표현해요 `/api/v1/interviews` 이런식으로요~

2023-08-19 11:14 UTC, f-lab-moony commented on src/main/java/com/example/interviewPrep/quiz/interview/domain/Interview.java
> +    @Column(name = "INTERVIEW_ID")
자신의 id는 컬럼명도 그냥 id로 하는게 좋지 않을까요 ?

2023-08-19 11:14 UTC, f-lab-moony commented on src/main/java/com/example/interviewPrep/quiz/interview/dto/request/InterviewRequest.java
> +    List<Answer> answers;
접근지정자가 빠져있네요 ~ 캡슐화가 안되면 어떤 단점이 있을까요 ?

2023-08-19 11:14 UTC, f-lab-moony commented on src/main/java/com/example/interviewPrep/quiz/interview/repository/InterviewRepository.java
> +    Interview save(Interview answer);
save는 굳이 만들어 줄 필요가 있을까요 ?

2023-08-19 11:14 UTC, f-lab-moony commented on src/main/java/com/example/interviewPrep/quiz/interview/service/InterviewService.java
> +        Member member = memberRepository.findById(memberId).orElse(null);
접속은 됐는데 실제 유저 정보 조회가 안되는상황으로 보이는데요, null로 받고 그냥 정상수행되는게 맞을까요 ?

2023-08-19 11:14 UTC, f-lab-moony commented on src/main/java/com/example/interviewPrep/quiz/interview/service/InterviewService.java
> +        interviewRepository.save(interview);
근데 이거 리파지토리에서 save 재정의하면 저장 잘 되나요 ?

2023-08-19 11:14 UTC, f-lab-moony commented on src/main/java/com/example/interviewPrep/quiz/interview/service/InterviewService.java
> +                .createdDate(customLocalDateTime(interview.getCreatedDate()))
`customLocalDateTime` 요건 뭐죠 ?

2023-08-19 11:14 UTC, f-lab-moony commented on src/main/java/com/example/interviewPrep/quiz/interview/service/InterviewService.java
> +
이런부분이 꽤 많네요 컨벤션 적용을 습관 들이시는게 좋을 것 같아요 ~ 전에 말씀드린 `save action` 플러그인도 한번 활용해보세요 ~

2023-08-20 08:57 UTC, LeeJaeYun7 commented on src/main/java/com/example/interviewPrep/quiz/MemberInterview/domain/MemberInterview.java
> +public class MemberInterview {
이 부분 잘못 생각한 것 같습니다. 
Member와 Interview는 1:N이 맞는 것 같습니다

2023-08-21 08:34 UTC, LeeJaeYun7 commented on src/main/java/com/example/interviewPrep/quiz/MemberInterview/domain/MemberInterview.java
> +@Setter
값이 이후에 임의로 변경될 수 있다는 단점이 있습니다

2023-08-21 08:35 UTC, LeeJaeYun7 commented on src/main/java/com/example/interviewPrep/quiz/MemberInterview/domain/MemberInterview.java
> +public class MemberInterview {
반영 료

2023-08-21 08:36 UTC, LeeJaeYun7 commented on src/main/java/com/example/interviewPrep/quiz/interview/controller/InterviewController.java
> +@CrossOrigin("*")
@CrossOrigin을 클래스별로 관리하는 이유에 대한 질문이실까요?
말씀하신대로 클래스별로 관리할 필요는 없고, 
애플리케이션 레벨에서 한 번 관리하면 될 것 같습니다!

2023-08-21 08:37 UTC, LeeJaeYun7 commented on src/main/java/com/example/interviewPrep/quiz/interview/controller/InterviewController.java
> +    public ResultResponse<?> createInterview(@RequestBody @Valid InterviewRequest interviewRequest){
지금은 @NotNull 등을 사용하지 않아서 동작하지 않습니다.
제거해야 할 것 같습니다

2023-08-21 08:39 UTC, LeeJaeYun7 commented on src/main/java/com/example/interviewPrep/quiz/interview/controller/InterviewController.java
> +    public ResultResponse<?> createInterview(@RequestBody @Valid InterviewRequest interviewRequest){
반영 완료

2023-08-21 08:39 UTC, LeeJaeYun7 commented on src/main/java/com/example/interviewPrep/quiz/interview/controller/InterviewController.java
> +    @PostMapping("/api/v1/interview")
넵 확인했습다

2023-08-21 08:40 UTC, LeeJaeYun7 commented on src/main/java/com/example/interviewPrep/quiz/interview/domain/Interview.java
> +    @Column(name = "INTERVIEW_ID")
넵 확인했습니다

2023-08-21 08:43 UTC, LeeJaeYun7 commented on src/main/java/com/example/interviewPrep/quiz/interview/dto/request/InterviewRequest.java
> +    List<Answer> answers;
다른 패키지의 클래스 혹은 다른 클래스에서 접근하여서 값이 쉽게 변경될 수 있다는 단점이 있습니다

2023-08-21 08:58 UTC, LeeJaeYun7 commented on src/main/java/com/example/interviewPrep/quiz/MemberInterview/domain/MemberInterview.java
> +public class MemberInterview {
반영 완료

2023-08-21 08:58 UTC, LeeJaeYun7 commented on src/main/java/com/example/interviewPrep/quiz/MemberInterview/domain/MemberInterview.java
> +public class MemberInterview {
반영 완료

2023-08-21 08:58 UTC, LeeJaeYun7 commented on src/main/java/com/example/interviewPrep/quiz/interview/controller/InterviewController.java
> +
넵 확인했습다

2023-08-21 08:59 UTC, LeeJaeYun7 commented on src/main/java/com/example/interviewPrep/quiz/interview/dto/request/InterviewRequest.java
> +    List<Answer> answers;
반영 완료

2023-08-21 09:00 UTC, LeeJaeYun7 commented on src/main/java/com/example/interviewPrep/quiz/interview/repository/InterviewRepository.java
> +    Interview save(Interview answer);
JpaRepository 가 CrudRepository를 상속 받고, 
CrudRepository에 save가 정의되어 있다는 점을 몰라서 이렇게 했던 것 같습니다.
수정하겠습니다.

2023-08-21 09:00 UTC, LeeJaeYun7 commented on src/main/java/com/example/interviewPrep/quiz/interview/repository/InterviewRepository.java
> +    Interview save(Interview answer);
반영 완료

2023-08-21 09:02 UTC, LeeJaeYun7 commented on src/main/java/com/example/interviewPrep/quiz/interview/service/InterviewService.java
> +        Member member = memberRepository.findById(memberId).orElse(null);
Exception 처리가 필요할 것 같습니다.
수정했습니다

2023-08-21 09:02 UTC, LeeJaeYun7 commented on src/main/java/com/example/interviewPrep/quiz/interview/service/InterviewService.java
> +        Member member = memberRepository.findById(memberId).orElse(null);
반영 완료

2023-08-21 09:03 UTC, LeeJaeYun7 commented on src/main/java/com/example/interviewPrep/quiz/interview/service/InterviewService.java
> +        interviewRepository.save(interview);
재정의한 save 메소드 삭제했습니다!

2023-08-21 09:03 UTC, LeeJaeYun7 commented on src/main/java/com/example/interviewPrep/quiz/interview/service/InterviewService.java
> +        interviewRepository.save(interview);
반영 완료

2023-08-21 09:03 UTC, LeeJaeYun7 commented on src/main/java/com/example/interviewPrep/quiz/interview/service/InterviewService.java
> +
반영 완료

2023-08-21 09:04 UTC, LeeJaeYun7 commented on src/main/java/com/example/interviewPrep/quiz/MemberInterview/domain/MemberInterview.java
> +@Setter
MemberInterview 엔티티 클래스를 삭제하기로 해서,
이 부분은 같이 제거될 것 같습니다

2023-08-21 09:04 UTC, LeeJaeYun7 commented on src/main/java/com/example/interviewPrep/quiz/MemberInterview/domain/MemberInterview.java
> +@Setter
반영 완료

2023-08-21 12:49 UTC, LeeJaeYun7 commented on src/main/java/com/example/interviewPrep/quiz/interview/service/InterviewService.java
> +                .createdDate(customLocalDateTime(interview.getCreatedDate()))
interview.getCreatedDate()가 LocalDateTime 타입인데,
String 타입으로 변환해주기 위해서 사용되는 것입니다!
![image](https://github.com/f-lab-edu/interviewPrep/assets/134198681/47e159e0-6b98-44bd-b1fd-215247fbf6e1)

2023-08-25 16:34 UTC, merged