#16 Heart 패키지 리팩토링
f-lab-edu/interviewPrep pull request #22
Opened 2023-08-29 04:36 UTC by LeeJaeYun7

- Heart 패키지에 대한 리팩토링을 진행하였습니다

2023-09-02 15:52 UTC, f-lab-moony requested changes
고생 많으셨습니다 ~
코멘트를 남겨 뒀는데, 저번 시간에 말씀드린 락 부분도 포함해서 한번 다시 다듬으시면 좋을 것 같아서 리뷰 재요청 드려요 ~

2023-09-02 15:52 UTC, f-lab-moony commented on src/main/java/com/example/interviewPrep/quiz/heart/domain/Heart.java
> +        this.id = id;
시퀀스 값인데 받을 필요가 있을까요 ~?

2023-09-02 15:52 UTC, f-lab-moony commented on src/main/java/com/example/interviewPrep/quiz/heart/service/HeartService.java
> +        Answer answer = answerRepository.findById(answerId).orElseThrow(() -> new CommonException(NOT_FOUND_ANSWER));
요런 부분은 Repository를 직접 참조하지 않고, Service를 참조하면 재사용이 가능하지 않을까요 ?

2023-09-02 15:52 UTC, f-lab-moony commented on src/main/java/com/example/interviewPrep/quiz/heart/service/HeartService.java
> +        Heart heart = checkHeartExists(answerId, memberId);
check~~ 메서드에서 boolean을 리턴하는게 낫지 않을까요 ?

2023-09-04 11:55 UTC, LeeJaeYun7 commented on src/main/java/com/example/interviewPrep/quiz/heart/domain/Heart.java
> +        this.id = id;
넵 확인했습니다

2023-09-04 12:02 UTC, LeeJaeYun7 commented on src/main/java/com/example/interviewPrep/quiz/heart/service/HeartService.java
> +        Answer answer = answerRepository.findById(answerId).orElseThrow(() -> new CommonException(NOT_FOUND_ANSWER));
넵 확인했습니다

2023-09-04 12:02 UTC, LeeJaeYun7 commented on src/main/java/com/example/interviewPrep/quiz/heart/service/HeartService.java
> +        Answer answer = answerRepository.findById(answerId).orElseThrow(() -> new CommonException(NOT_FOUND_ANSWER));
반영 완료

2023-09-04 12:02 UTC, LeeJaeYun7 commented on src/main/java/com/example/interviewPrep/quiz/heart/service/HeartService.java
> +        Heart heart = checkHeartExists(answerId, memberId);
넵 확인했습니다

2023-09-04 12:02 UTC, LeeJaeYun7 commented on src/main/java/com/example/interviewPrep/quiz/heart/service/HeartService.java
> +        Heart heart = checkHeartExists(answerId, memberId);
반영 완료

2023-09-08 16:52 UTC, f-lab-moony approved these changes
고생 많으셨습니다 ~
머지 하도록 할게요 ~

2023-09-08 16:52 UTC, f-lab-moony commented on src/main/java/com/example/interviewPrep/quiz/heart/domain/Heart.java
> +    public Heart(Answer answer, Member member) {
👍

2023-09-08 16:52 UTC, f-lab-moony commented on src/main/java/com/example/interviewPrep/quiz/heart/repository/AnswerLockRepository.java
> +    @Query(value = "select get_lock(:key, 3000)", nativeQuery = true)
timeout도 파라미터로 받는게 어떨까요 ~?

2023-09-08 16:52 UTC, f-lab-moony commented on src/main/java/com/example/interviewPrep/quiz/heart/service/HeartService.java
> +            answerLockRepository.releaseLock(answerId.toString());
위에 increaseAnswerHaertCnt 에서 SQL Exception이 발생하면, 이 구문은 실행 될까요 ?

2023-09-08 16:52 UTC, f-lab-moony commented on src/main/java/com/example/interviewPrep/quiz/question/service/ReferenceService.java
> +                // .heartCnt(heartRepository.countRefHeartByReferenceId(ref.getId()))
안쓰는거면 정리 해 주세요 ~

2023-09-08 16:52 UTC, merged