#21 Answer 패키지 테스트 리팩토링
f-lab-edu/interviewPrep pull request #28
Opened 2023-09-21 13:30 UTC by LeeJaeYun7

- Answer 패키지의 테스트를 리팩토링하였습니다.

2023-09-26 15:31 UTC, f-lab-moony requested changes
고생 많으셨습니다 ~
코멘트를 좀 남겨 뒀는데, 확인 후 리뷰 재요청 부탁드려요 ~

2023-09-26 15:31 UTC, f-lab-moony commented on src/main/java/com/example/interviewPrep/quiz/answer/domain/Answer.java
> +    public void setContent(String content){
내용 수정 시 사용되는 메서드 같은데, updateContent로 이름을 바꾸는 건 어떨까요 ?

2023-09-26 15:31 UTC, f-lab-moony commented on src/main/java/com/example/interviewPrep/quiz/answer/service/AnswerService.java
> +        Member answerMember = memberRepository.findById(memberId).orElse(null);
Answer의 member와 question이 null이어도 되는건가요 ?

2023-09-26 15:31 UTC, f-lab-moony commented on src/main/java/com/example/interviewPrep/quiz/answer/service/AnswerService.java
> +        if(answer.isEmpty()){
이부분 orElseThrow로 합칠 수 있을 것 같아요 ~

2023-09-26 15:31 UTC, f-lab-moony commented on src/main/java/com/example/interviewPrep/quiz/email/controller/EmailController.java
> +        Long memberId = jwtService.getMemberId();
이건 어디에 쓰이고 있나요 ?

2023-09-26 15:31 UTC, f-lab-moony commented on src/test/java/com/example/interviewPrep/quiz/Answer/controller/AnswerCreateWebControllerTest.java
> +    JwtUtil jwtUtil;
이거 사라지지 않았나요 ?

2023-09-26 15:31 UTC, f-lab-moony commented on src/test/java/com/example/interviewPrep/quiz/Answer/controller/AnswerCreateWebControllerTest.java
> +    CustomOAuth2UserService customOAuth2UserService;
다른 서비스들은 안쓰이는 거 아닌가요 ?

2023-09-26 15:31 UTC, f-lab-moony commented on src/test/java/com/example/interviewPrep/quiz/Answer/controller/AnswerCreateWebControllerTest.java
> +        verify(answerService).createAnswer(any(AnswerRequest.class));
이런 경우에는 any보다는 실제 요청이 잘 반환되었는지 파라미터 값도 검증하는게 좋을 것 같아요~

2023-09-26 15:31 UTC, f-lab-moony commented on src/test/java/com/example/interviewPrep/quiz/Answer/controller/AnswerCreateWebControllerTest.java
> +        AnswerRequest validAnswerRequest = AnswerRequest.builder()
valid랑 invalid랑 차이가 뭐에요 ?

2023-09-26 15:31 UTC, f-lab-moony commented on src/test/java/com/example/interviewPrep/quiz/Answer/dto/AnswerRequestTest.java
> +        assertThat(answerRequest.getContent()).isEqualTo("답안입니다.");
content만 확인하는 이유가 있을까요 ?

2023-09-28 06:33 UTC, LeeJaeYun7 commented on src/test/java/com/example/interviewPrep/quiz/Answer/controller/AnswerCreateWebControllerTest.java
> +    JwtUtil jwtUtil;
넵 피드백 반영했습니다

2023-09-28 11:56 UTC, LeeJaeYun7 commented on src/test/java/com/example/interviewPrep/quiz/Answer/controller/AnswerCreateWebControllerTest.java
> +    CustomOAuth2UserService customOAuth2UserService;
이거 안 넣어주면 에러가 나더라고요
아마 Spring Security 적용한 부분과 관련이 있는 것 같습니다

2023-09-28 11:57 UTC, LeeJaeYun7 commented on src/test/java/com/example/interviewPrep/quiz/Answer/controller/AnswerCreateWebControllerTest.java
> +        AnswerRequest validAnswerRequest = AnswerRequest.builder()
valid는 유효한 경우, invalid는 유효하지 않은 경우인데,
AnswerRequest DTO에서 Objects.requireNonNull로 검사한다고 해서
invalidRequest에 대한 테스트는 작성하지 않았습니다.
이건 빼도 괜찮을 것 같습니다

2023-10-01 15:30 UTC, LeeJaeYun7 commented on src/main/java/com/example/interviewPrep/quiz/answer/domain/Answer.java
> +    public void setContent(String content){
넵 updateContent로 하는 편이 좋을 것 같네요
수정하겠습니다

2023-10-01 15:33 UTC, LeeJaeYun7 commented on src/main/java/com/example/interviewPrep/quiz/answer/service/AnswerService.java
> +        Member answerMember = memberRepository.findById(memberId).orElse(null);
orElseThrow로 값이 없을 시 Exception을 리턴하도록 하는 편이 맞을 것 같습니다
수정했습니다

2023-10-01 15:38 UTC, LeeJaeYun7 commented on src/main/java/com/example/interviewPrep/quiz/answer/service/AnswerService.java
> +        if(answer.isEmpty()){
넵 그렇게 하는 편이 가독성 측면에서 나을 것 같습니다

2023-10-01 15:42 UTC, LeeJaeYun7 commented on src/main/java/com/example/interviewPrep/quiz/email/controller/EmailController.java
> +        Long memberId = jwtService.getMemberId();
memberId 변수가 따로 쓰이는 곳은 없어서, 저 변수는 불필요한 것 같습니다.
jwtService.getMemberId는 해당 메소드(이 경우 emailChangeConfirm)를 
멤버가 로그인한 상태에서만 사용할 수 있도록 제한하는 역할을 합니다.

2023-10-01 15:44 UTC, LeeJaeYun7 commented on src/test/java/com/example/interviewPrep/quiz/Answer/dto/AnswerRequestTest.java
> +        assertThat(answerRequest.getContent()).isEqualTo("답안입니다.");
questionId도 검증하도록 추가했습니다

2023-10-02 02:36 UTC, LeeJaeYun7 commented on src/test/java/com/example/interviewPrep/quiz/Answer/controller/AnswerCreateWebControllerTest.java
> +        verify(answerService).createAnswer(any(AnswerRequest.class));
해당 요청을 AnswerService 테스트 클래스에서 검증해서 여기서는 따로 필요 없을 것 같습니다~

2023-10-03 14:45 UTC, merged