#7 Sse알림 기능에 Redis 도입
f-lab-edu/interviewPrep pull request #8
Opened 2023-07-16 06:02 UTC by LeeJaeYun7

2023-07-17 17:06 UTC, f-lab-moony requested changes
고생 많으셨습니다!
피드백을 좀 남겨 두었는데, 확인 후에 머지 하도록 할게요 ~

2023-07-17 17:06 UTC, f-lab-moony commented on src/main/java/com/example/interviewPrep/quiz/notification/service/NotificationService.java
> +        }else{
컨벤션을 따로 설정을 안하신 것 같은데, [구글 스타일 적용](https://velog.io/@injoon2019/IntelliJ%EC%97%90-Google-Java-Style-Guide-%EC%A0%81%EC%9A%A9%ED%95%98%EA%B8%B0) 해보는 게 어떨까요 ?

2023-07-18 09:02 UTC, LeeJaeYun7 commented on src/main/java/com/example/interviewPrep/quiz/answer/domain/AnswerComment.java
> +    Notification notification;
음 제가 잘못한거 같네요. @OneToOne이 아니라 @OneToMany가 맞을 것 같습니다

2023-07-18 09:03 UTC, LeeJaeYun7 commented on src/main/java/com/example/interviewPrep/quiz/notification/service/NotificationService.java
> +        }else{
넵 이 부분 참고해보겠습니다

2023-07-18 09:16 UTC, LeeJaeYun7 commented on src/main/java/com/example/interviewPrep/quiz/answer/domain/AnswerComment.java
> +    Notification notification;
반영 완료

2023-07-18 09:26 UTC, LeeJaeYun7 commented on src/main/java/com/example/interviewPrep/quiz/notification/domain/Notification.java
> +@Setter
반영 완료

2023-07-18 09:40 UTC, LeeJaeYun7 commented on src/main/java/com/example/interviewPrep/quiz/notification/service/NotificationService.java
> +            for(Notification notification: notifications){
확인해보겠습니다

2023-07-18 09:43 UTC, LeeJaeYun7 commented on src/main/java/com/example/interviewPrep/quiz/notification/service/NotificationService.java
> +            for(Notification notification: notifications){
반영 완료

2023-07-18 09:51 UTC, LeeJaeYun7 commented on src/main/java/com/example/interviewPrep/quiz/notification/service/NotificationService.java
> +            System.out.println("emitterId는?" + id);
넵 확인했습니다

2023-07-18 09:52 UTC, LeeJaeYun7 commented on src/main/java/com/example/interviewPrep/quiz/notification/service/NotificationService.java
> +        else{
넵 확인했습니다

2023-07-18 09:53 UTC, LeeJaeYun7 commented on src/main/java/com/example/interviewPrep/quiz/notification/service/NotificationService.java
> +        else{
반영 완료

2023-07-18 09:56 UTC, LeeJaeYun7 commented on src/main/java/com/example/interviewPrep/quiz/notification/service/NotificationService.java
> +        return notification;
이 부분에서 버그가 발생해서 테스트 도중 이렇게 작성해서 커밋한것 같습니다.
현재 Notification Entity의 @Id 칼럼에 @GeneratedValue(strategy = GenerationType.IDENTITY)라고 설정되어 있는데,

notificationRepository.save(notification)으로 
생성된 notification 객체를 저장하려고 할 때, id가 null이라는 문제가 발생하더라고요 

제 생각에는 h2 데이터베이스에서 auto increment로 자동으로 생성해줘야 하는게 아닌가 싶었는데, 안되는 것 같아서 문제 해결중입니다

2023-07-24 04:08 UTC, f-lab-moony approved these changes
고생 많으셨습니다 ~ 머지 해둘게요!
라고 하려고 했는데 베이스 브랜치랑 충동리 나서 머지가 불가능하네요 ~? 혹시 따로 `main` 브랜치에 작업하셨을까요 ?

2023-07-24 04:08 UTC, f-lab-moony commented on src/main/java/com/example/interviewPrep/quiz/domain/BaseTimeEntity.java
> +    @JsonIgnore
`@JsonIgnore` 는 왜 추가가 됐을까요 ?

2023-07-24 06:17 UTC, LeeJaeYun7 commented on src/main/java/com/example/interviewPrep/quiz/domain/BaseTimeEntity.java
> +    @JsonIgnore
저 부분 때문에 Redis에서 직렬화, 역직렬화 할 때 에러가 발생하더라고요
그래서 추가했습니다!

2023-07-25 05:39 UTC, merged